web_server:
  server:
    rpc_client:
      port: 4040
      hostname: localhost
operations:
  #Redis
  REDIS_HOST: localhost
  REDIS_PORT:  6379
  NEWS_TABLE_NAME: news
  #Click_logs
  CLICK_LOGS_TABLE_NAME: click_logs
  NEWS_LIMIT: 100
  NEWS_LIST_BATCH_SIZE: 10
  USER_NEWS_TIME_OUT_IN_SECONDS: 60
  #Queue
  LOG_CLICKS_TASK_QUEUE_URL: amqp://yrpcjxza:t5GSd_55tVaZpK_hBtDk-92oXQ3jWML-@crocodile.rmq.cloudamqp.com/yrpcjxza
  LOG_CLICKS_TASK_QUEUE_NAME: log-clicks-task-queue

service:
  #RPC server
  SERVER_HOST: localhost
  SERVER_PORT: 4040

common:
  #cloudAMQP
  CLOUDAMQP_URL: amqp://zusbajmx:pRK2EOrKHha8m2YND7_XxenLwy1D3dPi@crocodile.rmq.cloudamqp.com/zusbajmx
  MONGO_DB_HOST: localhost
  MONGO_DB_PORT: 27017
  DB_NAME: tap-news
  NEWS_API_ENDPOINT: https://newsapi.org/v1/
  # Use your own API KEY
  NEWS_API_KEY: cab2625bf7e844fe8d323b81df3508a0
  ARTICALS_API: articles
  CNN: cnn
  SORT_BY_TOP: top
  CERTIFILE: False
  #news recommandation service
  news_recommendation_service_client:
    URL: http://localhost:5050/
  news_topic_modeling_service_client:
    URL: http://localhost:6060/
news_pipeline:
  NEWS_TABLE_NAME: news
  SLEEP_TIME_IN_SECONDS_DEDUPER: 1
  SAME_NEWS_SIMILARITY_THRESHOLD: 0.9
  # Use your own Cloud AMQP queue
  DEDUPE_NEWS_TASK_QUEUE_URL: amqp://etddpjvc:und83CUDNgDbfjHqiYzRivn-RQ79ITSe@crocodile.rmq.cloudamqp.com/etddpjvc
  DEDUPE_NEWS_TASK_QUEUE_NAME: tap-news-deduqe-new-task-queue
  SCRAPE_NEWS_TASK_QUEUE_URL: amqp://vqngbkyt:cI4yPGG-AGlCbc9sFRSf3Zjk5N1nSwLx@salamander.rmq.cloudamqp.com/vqngbkyt
  SCRAPE_NEWS_TASK_QUEUE_NAME: tap-news-scrape-news-task-queue
  SLEEP_TIME_IN_SECONDS_FETCHER: 5
  REDIS_HOST: localhost
  REDIS_PORT: 6379
  NEWS_TIME_OUT_IN_SECONDS: 86400
  SLEEP_TIME_IN_SECOUNDS_MONITOR: 10
  NEWS_SOURCES: [
    'bbc-news',
    'bbc-sport',
    'bloomberg',
    'cnn',
    'entertainment-weekly',
    'espn',
    'ign',
    'techcrunch',
    'the-new-york-times',
    'the-wall-street-journal',
    'the-washington-post'
  ]

news_recommendation_service:
  NUM_OF_CLASSES: 17
  INITIAL_P: 1.0
  ALPHA: 0.1
  SLEEP_TIME_IN_SECONDS: 1
  # Use your own queue
  LOG_CLICKS_TASK_QUEUE_URL: amqp://yrpcjxza:t5GSd_55tVaZpK_hBtDk-92oXQ3jWML-@crocodile.rmq.cloudamqp.com/yrpcjxza
  LOG_CLICKS_TASK_QUEUE_NAME: log-clicks-task-queue
  PREFERENCE_MODEL_TABLE_NAME: user_preference_model
  NEWS_TABLE_NAME: news
  SERVER_HOST: localhost
  SERVER_PORT: 5050

news_topic_modeling_service:
  server:
    SERVER_HOST: localhost
    SERVER_PORT: 6060
    MODEL_DIR: ../model
    MODEL_UPDATE_LAG_IN_SECONDS: 10
    N_CLASSES: 17
    VARS_FILE: ../model/vars
    VOCAB_PROCESSOR_SAVE_FILE: ../model/vocab_procesor_save_file
    n_words: 0
    MAX_DOCUMENT_LENGTH: 500
    vocab_processor: None
    classifier: None
  trainer:

